version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: trampantojo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trampantojo
    ports:
      - "5432:5432"
