[package]
name = "scoring"
version = "0.1.0"
edition = "2024"

[dependencies]
trampantojo-core = { path = "../core" }
storage = { path = "../storage" }
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls"] }
serde = { version = "1", features = ["derive"] }
tracing-subscriber = "0.3"
tracing = "0.1"
anyhow = "1.0"
dotenvy = "0.15"
